/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const Id = IDL.Nat;
export const RunStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'halted' : IDL.Null,
  'failed' : IDL.Null,
  'running' : IDL.Null,
});
export const FormatAdapterOutput = IDL.Record({
  'content' : IDL.Text,
  'characterLimit' : IDL.Nat,
  'platform' : IDL.Text,
  'aspectRatio' : IDL.Text,
});
export const VideoOutputStatus = IDL.Variant({
  'generating' : IDL.Null,
  'ready' : IDL.Null,
  'no_result' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const AgentKind = IDL.Variant({
  'writer' : IDL.Null,
  'continuity' : IDL.Null,
  'visual' : IDL.Null,
});
export const AgentOutput = IDL.Record({
  'content' : IDL.Text,
  'agent' : AgentKind,
});
export const MediaArtifactStatus = IDL.Variant({
  'generating' : IDL.Null,
  'ready' : IDL.Null,
  'failed' : IDL.Null,
});
export const MediaArtifact = IDL.Record({
  'status' : MediaArtifactStatus,
  'createdAt' : Timestamp,
  'mimeType' : IDL.Text,
  'durationSeconds' : IDL.Float64,
  'storageUrl' : IDL.Text,
  'characterId' : IDL.Opt(Id),
  'cameoId' : IDL.Opt(Id),
  'aspectRatio' : IDL.Text,
});
export const ProductionRun = IDL.Record({
  'id' : Id,
  'status' : RunStatus,
  'formatOutputs' : IDL.Vec(FormatAdapterOutput),
  'rawInput' : IDL.Text,
  'tokenCostBurn' : IDL.Float64,
  'videoStatus' : VideoOutputStatus,
  'timestamp' : Timestamp,
  'characterId' : IDL.Opt(Id),
  'generatedAssets' : IDL.Vec(AgentOutput),
  'mediaArtifact' : IDL.Opt(MediaArtifact),
  'promptId' : IDL.Opt(Id),
});
export const PatchStatus = IDL.Variant({
  'pending_approval' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const VersionTag = IDL.Text;
export const SuperSuitPatch = IDL.Record({
  'id' : Id,
  'status' : PatchStatus,
  'performanceDeltaMetrics' : IDL.Text,
  'proposedPromptPatch' : IDL.Text,
  'versionTag' : VersionTag,
  'createdAt' : Timestamp,
  'targetAgent' : AgentKind,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AttachMediaInput = IDL.Record({
  'mimeType' : IDL.Text,
  'durationSeconds' : IDL.Float64,
  'storageUrl' : IDL.Text,
  'cameoId' : IDL.Opt(Id),
  'runId' : Id,
  'aspectRatio' : IDL.Text,
});
export const DnaRecord = IDL.Record({
  'id' : Id,
  'visualMarkers' : IDL.Text,
  'activeVersion' : IDL.Nat,
  'characterName' : IDL.Text,
  'createdAt' : Timestamp,
  'identityBlocks' : IDL.Text,
  'immutableTraits' : IDL.Text,
});
export const ReplicateTokenStatus = IDL.Record({ 'configured' : IDL.Bool });
export const AssetKind = IDL.Variant({
  'audio' : IDL.Null,
  'video' : IDL.Null,
  'image' : IDL.Null,
});
export const AssetInput = IDL.Record({
  'linkedCharacterId' : IDL.Opt(Id),
  'tags' : IDL.Vec(IDL.Text),
  'fileName' : IDL.Text,
  'fileType' : AssetKind,
  'storageUrl' : IDL.Text,
});
export const AssetIngredient = IDL.Record({
  'id' : Id,
  'linkedCharacterId' : IDL.Opt(Id),
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'fileName' : IDL.Text,
  'fileType' : AssetKind,
  'storageUrl' : IDL.Text,
});
export const CameoInput = IDL.Record({
  'rightAssetId' : IDL.Opt(Id),
  'voiceAssetId' : IDL.Opt(Id),
  'leftAssetId' : IDL.Opt(Id),
  'frontAssetId' : IDL.Opt(Id),
  'characterId' : Id,
});
export const CameoStatus = IDL.Variant({
  'complete' : IDL.Null,
  'draft' : IDL.Null,
});
export const CameoCapture = IDL.Record({
  'id' : Id,
  'status' : CameoStatus,
  'rightAssetId' : IDL.Opt(Id),
  'voiceAssetId' : IDL.Opt(Id),
  'leftAssetId' : IDL.Opt(Id),
  'createdAt' : Timestamp,
  'frontAssetId' : IDL.Opt(Id),
  'characterId' : Id,
});
export const DnaInput = IDL.Record({
  'visualMarkers' : IDL.Text,
  'characterName' : IDL.Text,
  'identityBlocks' : IDL.Text,
  'immutableTraits' : IDL.Text,
});
export const LoreInput = IDL.Record({
  'ruleName' : IDL.Text,
  'timelineConstraints' : IDL.Text,
  'universeBounds' : IDL.Text,
});
export const LoreStatus = IDL.Variant({
  'active' : IDL.Null,
  'deprecated' : IDL.Null,
});
export const LoreRule = IDL.Record({
  'id' : Id,
  'ruleName' : IDL.Text,
  'status' : LoreStatus,
  'createdAt' : Timestamp,
  'timelineConstraints' : IDL.Text,
  'universeBounds' : IDL.Text,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const AgentVersion = IDL.Record({
  'agent' : AgentKind,
  'history' : IDL.Vec(VersionTag),
  'currentVersion' : VersionTag,
});
export const CostTelemetry = IDL.Record({
  'averageCostPerRun' : IDL.Float64,
  'totalRuns' : IDL.Nat,
  'totalTokenCostBurn' : IDL.Float64,
});
export const EntropyState = IDL.Record({
  'recentUpdateTimestamps' : IDL.Vec(Timestamp),
  'maxUpdatesPerHour' : IDL.Nat,
});
export const Revision = IDL.Record({
  'formatOutputs' : IDL.Vec(FormatAdapterOutput),
  'tokenCostBurn' : IDL.Float64,
  'timestamp' : Timestamp,
  'instruction' : IDL.Opt(IDL.Text),
  'revisionNumber' : IDL.Nat,
  'generatedAssets' : IDL.Vec(AgentOutput),
});
export const RunDecision = IDL.Variant({
  'in_progress' : IDL.Null,
  'completed' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const RunDecisionState = IDL.Record({
  'decision' : RunDecision,
  'rejectionReason' : IDL.Opt(IDL.Text),
  'acceptedRevision' : IDL.Opt(IDL.Nat),
});
export const VideoGenerationStatus = IDL.Variant({
  'generating' : IDL.Null,
  'not_started' : IDL.Null,
  'ready' : IDL.Null,
  'no_result' : IDL.Null,
  'failed' : IDL.Null,
});
export const VideoGeneration = IDL.Record({
  'status' : VideoGenerationStatus,
  'startedAt' : Timestamp,
  'predictionId' : IDL.Opt(IDL.Text),
  'error' : IDL.Opt(IDL.Text),
  'prompt' : IDL.Text,
  'promptIndex' : IDL.Nat,
  'finishedAt' : IDL.Opt(Timestamp),
  'modelId' : IDL.Text,
  'runId' : Id,
});
export const VideoPromptOption = IDL.Record({
  'content' : IDL.Text,
  'agent' : IDL.Text,
  'index' : IDL.Nat,
});
export const RunSummary = IDL.Record({
  'id' : Id,
  'status' : RunStatus,
  'tokenCostBurn' : IDL.Float64,
  'timestamp' : Timestamp,
  'characterId' : IDL.Opt(Id),
});
export const SimulationStep = IDL.Variant({
  'asset_binding' : IDL.Null,
  'fracture' : IDL.Null,
  'lore_check' : IDL.Null,
  'ingestion' : IDL.Null,
  'dna_crossref' : IDL.Null,
});
export const SimulationLog = IDL.Record({
  'id' : Id,
  'rawInput' : IDL.Text,
  'stepName' : SimulationStep,
  'timestamp' : Timestamp,
  'evaluationOutput' : IDL.Text,
  'runId' : Id,
});
export const VideoModel = IDL.Record({
  'id' : IDL.Text,
  'provider' : IDL.Text,
  'premium' : IDL.Bool,
  'name' : IDL.Text,
  'default' : IDL.Bool,
});
export const RerunVideoGenerationInput = IDL.Record({
  'promptIndex' : IDL.Opt(IDL.Nat),
  'modelId' : IDL.Opt(IDL.Text),
  'runId' : Id,
});
export const RunInput = IDL.Record({
  'rawInput' : IDL.Text,
  'assetIngredientIds' : IDL.Vec(Id),
  'characterId' : IDL.Opt(Id),
});
export const StartVideoGenerationInput = IDL.Record({
  'promptIndex' : IDL.Opt(IDL.Nat),
  'modelId' : IDL.Opt(IDL.Text),
  'runId' : Id,
});
export const TweakInput = IDL.Record({
  'instruction' : IDL.Text,
  'runId' : Id,
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpRequestResult = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpRequestResult,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'acceptRun' : IDL.Func([Id, IDL.Nat], [IDL.Opt(ProductionRun)], []),
  'approveSuperSuitPatch' : IDL.Func([Id], [IDL.Opt(SuperSuitPatch)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'attachMediaArtifact' : IDL.Func(
      [AttachMediaInput],
      [IDL.Opt(ProductionRun)],
      [],
    ),
  'bumpDnaVersion' : IDL.Func([Id], [IDL.Opt(DnaRecord)], []),
  'clearReplicateToken' : IDL.Func([], [ReplicateTokenStatus], []),
  'continueRun' : IDL.Func([Id, IDL.Nat], [IDL.Opt(ProductionRun)], []),
  'createAsset' : IDL.Func([AssetInput], [AssetIngredient], []),
  'createCameo' : IDL.Func([CameoInput], [CameoCapture], []),
  'createDna' : IDL.Func([DnaInput], [DnaRecord], []),
  'createLore' : IDL.Func([LoreInput], [LoreRule], []),
  'deleteAsset' : IDL.Func([Id], [IDL.Bool], []),
  'deleteCameo' : IDL.Func([Id], [IDL.Bool], []),
  'deleteDna' : IDL.Func([Id], [IDL.Bool], []),
  'deleteLore' : IDL.Func([Id], [IDL.Bool], []),
  'deleteMediaArtifact' : IDL.Func([Id], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getAgentVersion' : IDL.Func([AgentKind], [IDL.Opt(AgentVersion)], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getAsset' : IDL.Func([Id], [IDL.Opt(AssetIngredient)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCameo' : IDL.Func([Id], [IDL.Opt(CameoCapture)], ['query']),
  'getCostTelemetry' : IDL.Func([], [CostTelemetry], ['query']),
  'getDna' : IDL.Func([Id], [IDL.Opt(DnaRecord)], ['query']),
  'getEntropyState' : IDL.Func([], [EntropyState], ['query']),
  'getLore' : IDL.Func([Id], [IDL.Opt(LoreRule)], ['query']),
  'getMediaArtifact' : IDL.Func([Id], [IDL.Opt(MediaArtifact)], ['query']),
  'getReplicateTokenStatus' : IDL.Func([], [ReplicateTokenStatus], ['query']),
  'getRevision' : IDL.Func([Id, IDL.Nat], [IDL.Opt(Revision)], ['query']),
  'getRun' : IDL.Func([Id], [IDL.Opt(ProductionRun)], ['query']),
  'getRunDecision' : IDL.Func([Id], [IDL.Opt(RunDecisionState)], ['query']),
  'getSuperSuitPatch' : IDL.Func([Id], [IDL.Opt(SuperSuitPatch)], ['query']),
  'getVideoGeneration' : IDL.Func([Id], [IDL.Opt(VideoGeneration)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAssets' : IDL.Func([], [IDL.Vec(AssetIngredient)], ['query']),
  'listAssetsForCharacter' : IDL.Func(
      [Id],
      [IDL.Vec(AssetIngredient)],
      ['query'],
    ),
  'listCameos' : IDL.Func([], [IDL.Vec(CameoCapture)], ['query']),
  'listCameosForCharacter' : IDL.Func([Id], [IDL.Vec(CameoCapture)], ['query']),
  'listDna' : IDL.Func([], [IDL.Vec(DnaRecord)], ['query']),
  'listLore' : IDL.Func([], [IDL.Vec(LoreRule)], ['query']),
  'listRevisions' : IDL.Func([Id], [IDL.Vec(Revision)], ['query']),
  'listRunDecisions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Id, RunDecisionState))],
      ['query'],
    ),
  'listRunPrompts' : IDL.Func([Id], [IDL.Vec(VideoPromptOption)], ['query']),
  'listRuns' : IDL.Func([], [IDL.Vec(RunSummary)], ['query']),
  'listSimulationLogs' : IDL.Func([Id], [IDL.Vec(SimulationLog)], ['query']),
  'listSuperSuitPatches' : IDL.Func([], [IDL.Vec(SuperSuitPatch)], ['query']),
  'listVideoModels' : IDL.Func([], [IDL.Vec(VideoModel)], ['query']),
  'pollVideoGeneration' : IDL.Func([Id], [IDL.Opt(VideoGeneration)], []),
  'recoverVideoGeneration' : IDL.Func([Id], [IDL.Opt(VideoGeneration)], []),
  'rejectRun' : IDL.Func([Id, IDL.Opt(IDL.Text)], [IDL.Opt(ProductionRun)], []),
  'rejectSuperSuitPatch' : IDL.Func([Id], [IDL.Opt(SuperSuitPatch)], []),
  'rerunVideoGeneration' : IDL.Func(
      [RerunVideoGenerationInput],
      [IDL.Opt(VideoGeneration)],
      [],
    ),
  'rollbackAgentVersion' : IDL.Func([AgentKind], [IDL.Opt(AgentVersion)], []),
  'runCriticAgent' : IDL.Func([], [IDL.Opt(SuperSuitPatch)], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setLoreStatus' : IDL.Func([Id, LoreStatus], [IDL.Opt(LoreRule)], []),
  'setReplicateToken' : IDL.Func([IDL.Text], [ReplicateTokenStatus], []),
  'startProductionRun' : IDL.Func([RunInput], [ProductionRun], []),
  'startVideoGeneration' : IDL.Func(
      [StartVideoGenerationInput],
      [IDL.Opt(VideoGeneration)],
      [],
    ),
  'submitTweak' : IDL.Func([TweakInput], [IDL.Opt(Revision)], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAsset' : IDL.Func([Id, AssetInput], [IDL.Opt(AssetIngredient)], []),
  'updateCameo' : IDL.Func([Id, CameoInput], [IDL.Opt(CameoCapture)], []),
  'updateDna' : IDL.Func([Id, DnaInput], [IDL.Opt(DnaRecord)], []),
  'updateLore' : IDL.Func([Id, LoreInput], [IDL.Opt(LoreRule)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const Id = IDL.Nat;
  const RunStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'halted' : IDL.Null,
    'failed' : IDL.Null,
    'running' : IDL.Null,
  });
  const FormatAdapterOutput = IDL.Record({
    'content' : IDL.Text,
    'characterLimit' : IDL.Nat,
    'platform' : IDL.Text,
    'aspectRatio' : IDL.Text,
  });
  const VideoOutputStatus = IDL.Variant({
    'generating' : IDL.Null,
    'ready' : IDL.Null,
    'no_result' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const AgentKind = IDL.Variant({
    'writer' : IDL.Null,
    'continuity' : IDL.Null,
    'visual' : IDL.Null,
  });
  const AgentOutput = IDL.Record({ 'content' : IDL.Text, 'agent' : AgentKind });
  const MediaArtifactStatus = IDL.Variant({
    'generating' : IDL.Null,
    'ready' : IDL.Null,
    'failed' : IDL.Null,
  });
  const MediaArtifact = IDL.Record({
    'status' : MediaArtifactStatus,
    'createdAt' : Timestamp,
    'mimeType' : IDL.Text,
    'durationSeconds' : IDL.Float64,
    'storageUrl' : IDL.Text,
    'characterId' : IDL.Opt(Id),
    'cameoId' : IDL.Opt(Id),
    'aspectRatio' : IDL.Text,
  });
  const ProductionRun = IDL.Record({
    'id' : Id,
    'status' : RunStatus,
    'formatOutputs' : IDL.Vec(FormatAdapterOutput),
    'rawInput' : IDL.Text,
    'tokenCostBurn' : IDL.Float64,
    'videoStatus' : VideoOutputStatus,
    'timestamp' : Timestamp,
    'characterId' : IDL.Opt(Id),
    'generatedAssets' : IDL.Vec(AgentOutput),
    'mediaArtifact' : IDL.Opt(MediaArtifact),
    'promptId' : IDL.Opt(Id),
  });
  const PatchStatus = IDL.Variant({
    'pending_approval' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const VersionTag = IDL.Text;
  const SuperSuitPatch = IDL.Record({
    'id' : Id,
    'status' : PatchStatus,
    'performanceDeltaMetrics' : IDL.Text,
    'proposedPromptPatch' : IDL.Text,
    'versionTag' : VersionTag,
    'createdAt' : Timestamp,
    'targetAgent' : AgentKind,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AttachMediaInput = IDL.Record({
    'mimeType' : IDL.Text,
    'durationSeconds' : IDL.Float64,
    'storageUrl' : IDL.Text,
    'cameoId' : IDL.Opt(Id),
    'runId' : Id,
    'aspectRatio' : IDL.Text,
  });
  const DnaRecord = IDL.Record({
    'id' : Id,
    'visualMarkers' : IDL.Text,
    'activeVersion' : IDL.Nat,
    'characterName' : IDL.Text,
    'createdAt' : Timestamp,
    'identityBlocks' : IDL.Text,
    'immutableTraits' : IDL.Text,
  });
  const ReplicateTokenStatus = IDL.Record({ 'configured' : IDL.Bool });
  const AssetKind = IDL.Variant({
    'audio' : IDL.Null,
    'video' : IDL.Null,
    'image' : IDL.Null,
  });
  const AssetInput = IDL.Record({
    'linkedCharacterId' : IDL.Opt(Id),
    'tags' : IDL.Vec(IDL.Text),
    'fileName' : IDL.Text,
    'fileType' : AssetKind,
    'storageUrl' : IDL.Text,
  });
  const AssetIngredient = IDL.Record({
    'id' : Id,
    'linkedCharacterId' : IDL.Opt(Id),
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'fileName' : IDL.Text,
    'fileType' : AssetKind,
    'storageUrl' : IDL.Text,
  });
  const CameoInput = IDL.Record({
    'rightAssetId' : IDL.Opt(Id),
    'voiceAssetId' : IDL.Opt(Id),
    'leftAssetId' : IDL.Opt(Id),
    'frontAssetId' : IDL.Opt(Id),
    'characterId' : Id,
  });
  const CameoStatus = IDL.Variant({
    'complete' : IDL.Null,
    'draft' : IDL.Null,
  });
  const CameoCapture = IDL.Record({
    'id' : Id,
    'status' : CameoStatus,
    'rightAssetId' : IDL.Opt(Id),
    'voiceAssetId' : IDL.Opt(Id),
    'leftAssetId' : IDL.Opt(Id),
    'createdAt' : Timestamp,
    'frontAssetId' : IDL.Opt(Id),
    'characterId' : Id,
  });
  const DnaInput = IDL.Record({
    'visualMarkers' : IDL.Text,
    'characterName' : IDL.Text,
    'identityBlocks' : IDL.Text,
    'immutableTraits' : IDL.Text,
  });
  const LoreInput = IDL.Record({
    'ruleName' : IDL.Text,
    'timelineConstraints' : IDL.Text,
    'universeBounds' : IDL.Text,
  });
  const LoreStatus = IDL.Variant({
    'active' : IDL.Null,
    'deprecated' : IDL.Null,
  });
  const LoreRule = IDL.Record({
    'id' : Id,
    'ruleName' : IDL.Text,
    'status' : LoreStatus,
    'createdAt' : Timestamp,
    'timelineConstraints' : IDL.Text,
    'universeBounds' : IDL.Text,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const AgentVersion = IDL.Record({
    'agent' : AgentKind,
    'history' : IDL.Vec(VersionTag),
    'currentVersion' : VersionTag,
  });
  const CostTelemetry = IDL.Record({
    'averageCostPerRun' : IDL.Float64,
    'totalRuns' : IDL.Nat,
    'totalTokenCostBurn' : IDL.Float64,
  });
  const EntropyState = IDL.Record({
    'recentUpdateTimestamps' : IDL.Vec(Timestamp),
    'maxUpdatesPerHour' : IDL.Nat,
  });
  const Revision = IDL.Record({
    'formatOutputs' : IDL.Vec(FormatAdapterOutput),
    'tokenCostBurn' : IDL.Float64,
    'timestamp' : Timestamp,
    'instruction' : IDL.Opt(IDL.Text),
    'revisionNumber' : IDL.Nat,
    'generatedAssets' : IDL.Vec(AgentOutput),
  });
  const RunDecision = IDL.Variant({
    'in_progress' : IDL.Null,
    'completed' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const RunDecisionState = IDL.Record({
    'decision' : RunDecision,
    'rejectionReason' : IDL.Opt(IDL.Text),
    'acceptedRevision' : IDL.Opt(IDL.Nat),
  });
  const VideoGenerationStatus = IDL.Variant({
    'generating' : IDL.Null,
    'not_started' : IDL.Null,
    'ready' : IDL.Null,
    'no_result' : IDL.Null,
    'failed' : IDL.Null,
  });
  const VideoGeneration = IDL.Record({
    'status' : VideoGenerationStatus,
    'startedAt' : Timestamp,
    'predictionId' : IDL.Opt(IDL.Text),
    'error' : IDL.Opt(IDL.Text),
    'prompt' : IDL.Text,
    'promptIndex' : IDL.Nat,
    'finishedAt' : IDL.Opt(Timestamp),
    'modelId' : IDL.Text,
    'runId' : Id,
  });
  const VideoPromptOption = IDL.Record({
    'content' : IDL.Text,
    'agent' : IDL.Text,
    'index' : IDL.Nat,
  });
  const RunSummary = IDL.Record({
    'id' : Id,
    'status' : RunStatus,
    'tokenCostBurn' : IDL.Float64,
    'timestamp' : Timestamp,
    'characterId' : IDL.Opt(Id),
  });
  const SimulationStep = IDL.Variant({
    'asset_binding' : IDL.Null,
    'fracture' : IDL.Null,
    'lore_check' : IDL.Null,
    'ingestion' : IDL.Null,
    'dna_crossref' : IDL.Null,
  });
  const SimulationLog = IDL.Record({
    'id' : Id,
    'rawInput' : IDL.Text,
    'stepName' : SimulationStep,
    'timestamp' : Timestamp,
    'evaluationOutput' : IDL.Text,
    'runId' : Id,
  });
  const VideoModel = IDL.Record({
    'id' : IDL.Text,
    'provider' : IDL.Text,
    'premium' : IDL.Bool,
    'name' : IDL.Text,
    'default' : IDL.Bool,
  });
  const RerunVideoGenerationInput = IDL.Record({
    'promptIndex' : IDL.Opt(IDL.Nat),
    'modelId' : IDL.Opt(IDL.Text),
    'runId' : Id,
  });
  const RunInput = IDL.Record({
    'rawInput' : IDL.Text,
    'assetIngredientIds' : IDL.Vec(Id),
    'characterId' : IDL.Opt(Id),
  });
  const StartVideoGenerationInput = IDL.Record({
    'promptIndex' : IDL.Opt(IDL.Nat),
    'modelId' : IDL.Opt(IDL.Text),
    'runId' : Id,
  });
  const TweakInput = IDL.Record({ 'instruction' : IDL.Text, 'runId' : Id });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'acceptRun' : IDL.Func([Id, IDL.Nat], [IDL.Opt(ProductionRun)], []),
    'approveSuperSuitPatch' : IDL.Func([Id], [IDL.Opt(SuperSuitPatch)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'attachMediaArtifact' : IDL.Func(
        [AttachMediaInput],
        [IDL.Opt(ProductionRun)],
        [],
      ),
    'bumpDnaVersion' : IDL.Func([Id], [IDL.Opt(DnaRecord)], []),
    'clearReplicateToken' : IDL.Func([], [ReplicateTokenStatus], []),
    'continueRun' : IDL.Func([Id, IDL.Nat], [IDL.Opt(ProductionRun)], []),
    'createAsset' : IDL.Func([AssetInput], [AssetIngredient], []),
    'createCameo' : IDL.Func([CameoInput], [CameoCapture], []),
    'createDna' : IDL.Func([DnaInput], [DnaRecord], []),
    'createLore' : IDL.Func([LoreInput], [LoreRule], []),
    'deleteAsset' : IDL.Func([Id], [IDL.Bool], []),
    'deleteCameo' : IDL.Func([Id], [IDL.Bool], []),
    'deleteDna' : IDL.Func([Id], [IDL.Bool], []),
    'deleteLore' : IDL.Func([Id], [IDL.Bool], []),
    'deleteMediaArtifact' : IDL.Func([Id], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getAgentVersion' : IDL.Func(
        [AgentKind],
        [IDL.Opt(AgentVersion)],
        ['query'],
      ),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getAsset' : IDL.Func([Id], [IDL.Opt(AssetIngredient)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCameo' : IDL.Func([Id], [IDL.Opt(CameoCapture)], ['query']),
    'getCostTelemetry' : IDL.Func([], [CostTelemetry], ['query']),
    'getDna' : IDL.Func([Id], [IDL.Opt(DnaRecord)], ['query']),
    'getEntropyState' : IDL.Func([], [EntropyState], ['query']),
    'getLore' : IDL.Func([Id], [IDL.Opt(LoreRule)], ['query']),
    'getMediaArtifact' : IDL.Func([Id], [IDL.Opt(MediaArtifact)], ['query']),
    'getReplicateTokenStatus' : IDL.Func([], [ReplicateTokenStatus], ['query']),
    'getRevision' : IDL.Func([Id, IDL.Nat], [IDL.Opt(Revision)], ['query']),
    'getRun' : IDL.Func([Id], [IDL.Opt(ProductionRun)], ['query']),
    'getRunDecision' : IDL.Func([Id], [IDL.Opt(RunDecisionState)], ['query']),
    'getSuperSuitPatch' : IDL.Func([Id], [IDL.Opt(SuperSuitPatch)], ['query']),
    'getVideoGeneration' : IDL.Func(
        [Id],
        [IDL.Opt(VideoGeneration)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAssets' : IDL.Func([], [IDL.Vec(AssetIngredient)], ['query']),
    'listAssetsForCharacter' : IDL.Func(
        [Id],
        [IDL.Vec(AssetIngredient)],
        ['query'],
      ),
    'listCameos' : IDL.Func([], [IDL.Vec(CameoCapture)], ['query']),
    'listCameosForCharacter' : IDL.Func(
        [Id],
        [IDL.Vec(CameoCapture)],
        ['query'],
      ),
    'listDna' : IDL.Func([], [IDL.Vec(DnaRecord)], ['query']),
    'listLore' : IDL.Func([], [IDL.Vec(LoreRule)], ['query']),
    'listRevisions' : IDL.Func([Id], [IDL.Vec(Revision)], ['query']),
    'listRunDecisions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Id, RunDecisionState))],
        ['query'],
      ),
    'listRunPrompts' : IDL.Func([Id], [IDL.Vec(VideoPromptOption)], ['query']),
    'listRuns' : IDL.Func([], [IDL.Vec(RunSummary)], ['query']),
    'listSimulationLogs' : IDL.Func([Id], [IDL.Vec(SimulationLog)], ['query']),
    'listSuperSuitPatches' : IDL.Func([], [IDL.Vec(SuperSuitPatch)], ['query']),
    'listVideoModels' : IDL.Func([], [IDL.Vec(VideoModel)], ['query']),
    'pollVideoGeneration' : IDL.Func([Id], [IDL.Opt(VideoGeneration)], []),
    'recoverVideoGeneration' : IDL.Func([Id], [IDL.Opt(VideoGeneration)], []),
    'rejectRun' : IDL.Func(
        [Id, IDL.Opt(IDL.Text)],
        [IDL.Opt(ProductionRun)],
        [],
      ),
    'rejectSuperSuitPatch' : IDL.Func([Id], [IDL.Opt(SuperSuitPatch)], []),
    'rerunVideoGeneration' : IDL.Func(
        [RerunVideoGenerationInput],
        [IDL.Opt(VideoGeneration)],
        [],
      ),
    'rollbackAgentVersion' : IDL.Func([AgentKind], [IDL.Opt(AgentVersion)], []),
    'runCriticAgent' : IDL.Func([], [IDL.Opt(SuperSuitPatch)], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setLoreStatus' : IDL.Func([Id, LoreStatus], [IDL.Opt(LoreRule)], []),
    'setReplicateToken' : IDL.Func([IDL.Text], [ReplicateTokenStatus], []),
    'startProductionRun' : IDL.Func([RunInput], [ProductionRun], []),
    'startVideoGeneration' : IDL.Func(
        [StartVideoGenerationInput],
        [IDL.Opt(VideoGeneration)],
        [],
      ),
    'submitTweak' : IDL.Func([TweakInput], [IDL.Opt(Revision)], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAsset' : IDL.Func([Id, AssetInput], [IDL.Opt(AssetIngredient)], []),
    'updateCameo' : IDL.Func([Id, CameoInput], [IDL.Opt(CameoCapture)], []),
    'updateDna' : IDL.Func([Id, DnaInput], [IDL.Opt(DnaRecord)], []),
    'updateLore' : IDL.Func([Id, LoreInput], [IDL.Opt(LoreRule)], []),
  });
};

export const init = ({ IDL }) => { return []; };