/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AgentKind = { 'writer' : null } |
  { 'continuity' : null } |
  { 'visual' : null };
export interface AgentOutput { 'content' : string, 'agent' : AgentKind }
export interface AgentVersion {
  'agent' : AgentKind,
  'history' : Array<VersionTag>,
  'currentVersion' : VersionTag,
}
export interface AssetIngredient {
  'id' : Id,
  'linkedCharacterId' : [] | [Id],
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'fileName' : string,
  'fileType' : AssetKind,
  'storageUrl' : string,
}
export interface AssetInput {
  'linkedCharacterId' : [] | [Id],
  'tags' : Array<string>,
  'fileName' : string,
  'fileType' : AssetKind,
  'storageUrl' : string,
}
export type AssetKind = { 'audio' : null } |
  { 'video' : null } |
  { 'image' : null };
export interface AttachMediaInput {
  'mimeType' : string,
  'durationSeconds' : number,
  'storageUrl' : string,
  'cameoId' : [] | [Id],
  'runId' : Id,
  'aspectRatio' : string,
}
export interface CameoCapture {
  'id' : Id,
  'status' : CameoStatus,
  'rightAssetId' : [] | [Id],
  'voiceAssetId' : [] | [Id],
  'leftAssetId' : [] | [Id],
  'createdAt' : Timestamp,
  'frontAssetId' : [] | [Id],
  'characterId' : Id,
}
export interface CameoInput {
  'rightAssetId' : [] | [Id],
  'voiceAssetId' : [] | [Id],
  'leftAssetId' : [] | [Id],
  'frontAssetId' : [] | [Id],
  'characterId' : Id,
}
export type CameoStatus = { 'complete' : null } |
  { 'draft' : null };
export interface Cell { 'value' : Value, 'name' : string }
export interface CostTelemetry {
  'averageCostPerRun' : number,
  'totalRuns' : bigint,
  'totalTokenCostBurn' : number,
}
export interface DnaInput {
  'visualMarkers' : string,
  'characterName' : string,
  'identityBlocks' : string,
  'immutableTraits' : string,
}
export interface DnaRecord {
  'id' : Id,
  'visualMarkers' : string,
  'activeVersion' : bigint,
  'characterName' : string,
  'createdAt' : Timestamp,
  'identityBlocks' : string,
  'immutableTraits' : string,
}
export interface EntropyState {
  'recentUpdateTimestamps' : Array<Timestamp>,
  'maxUpdatesPerHour' : bigint,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface FormatAdapterOutput {
  'content' : string,
  'characterLimit' : bigint,
  'platform' : string,
  'aspectRatio' : string,
}
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type Id = bigint;
export interface LoreInput {
  'ruleName' : string,
  'timelineConstraints' : string,
  'universeBounds' : string,
}
export interface LoreRule {
  'id' : Id,
  'ruleName' : string,
  'status' : LoreStatus,
  'createdAt' : Timestamp,
  'timelineConstraints' : string,
  'universeBounds' : string,
}
export type LoreStatus = { 'active' : null } |
  { 'deprecated' : null };
export interface MediaArtifact {
  'status' : MediaArtifactStatus,
  'createdAt' : Timestamp,
  'mimeType' : string,
  'durationSeconds' : number,
  'storageUrl' : string,
  'characterId' : [] | [Id],
  'cameoId' : [] | [Id],
  'aspectRatio' : string,
}
export type MediaArtifactStatus = { 'generating' : null } |
  { 'ready' : null } |
  { 'failed' : null };
export type PatchStatus = { 'pending_approval' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ProductionRun {
  'id' : Id,
  'status' : RunStatus,
  'formatOutputs' : Array<FormatAdapterOutput>,
  'rawInput' : string,
  'tokenCostBurn' : number,
  'videoStatus' : VideoOutputStatus,
  'timestamp' : Timestamp,
  'characterId' : [] | [Id],
  'generatedAssets' : Array<AgentOutput>,
  'mediaArtifact' : [] | [MediaArtifact],
  'promptId' : [] | [Id],
}
export interface ReplicateTokenStatus { 'configured' : boolean }
export interface RerunVideoGenerationInput {
  'promptIndex' : [] | [bigint],
  'modelId' : [] | [string],
  'runId' : Id,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface Revision {
  'formatOutputs' : Array<FormatAdapterOutput>,
  'tokenCostBurn' : number,
  'timestamp' : Timestamp,
  'instruction' : [] | [string],
  'revisionNumber' : bigint,
  'generatedAssets' : Array<AgentOutput>,
}
export type RunDecision = { 'in_progress' : null } |
  { 'completed' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface RunDecisionState {
  'decision' : RunDecision,
  'rejectionReason' : [] | [string],
  'acceptedRevision' : [] | [bigint],
}
export interface RunInput {
  'rawInput' : string,
  'assetIngredientIds' : Array<Id>,
  'characterId' : [] | [Id],
}
export type RunStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'halted' : null } |
  { 'failed' : null } |
  { 'running' : null };
export interface RunSummary {
  'id' : Id,
  'status' : RunStatus,
  'tokenCostBurn' : number,
  'timestamp' : Timestamp,
  'characterId' : [] | [Id],
}
export interface SimulationLog {
  'id' : Id,
  'rawInput' : string,
  'stepName' : SimulationStep,
  'timestamp' : Timestamp,
  'evaluationOutput' : string,
  'runId' : Id,
}
export type SimulationStep = { 'asset_binding' : null } |
  { 'fracture' : null } |
  { 'lore_check' : null } |
  { 'ingestion' : null } |
  { 'dna_crossref' : null };
export interface StartVideoGenerationInput {
  'promptIndex' : [] | [bigint],
  'modelId' : [] | [string],
  'runId' : Id,
}
export interface SuperSuitPatch {
  'id' : Id,
  'status' : PatchStatus,
  'performanceDeltaMetrics' : string,
  'proposedPromptPatch' : string,
  'versionTag' : VersionTag,
  'createdAt' : Timestamp,
  'targetAgent' : AgentKind,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface TweakInput { 'instruction' : string, 'runId' : Id }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export type VersionTag = string;
export interface VideoGeneration {
  'status' : VideoGenerationStatus,
  'startedAt' : Timestamp,
  'predictionId' : [] | [string],
  'error' : [] | [string],
  'prompt' : string,
  'promptIndex' : bigint,
  'finishedAt' : [] | [Timestamp],
  'modelId' : string,
  'runId' : Id,
}
export type VideoGenerationStatus = { 'generating' : null } |
  { 'not_started' : null } |
  { 'ready' : null } |
  { 'no_result' : null } |
  { 'failed' : null };
export interface VideoModel {
  'id' : string,
  'provider' : string,
  'premium' : boolean,
  'name' : string,
  'default' : boolean,
}
export type VideoOutputStatus = { 'generating' : null } |
  { 'ready' : null } |
  { 'no_result' : null };
export interface VideoPromptOption {
  'content' : string,
  'agent' : string,
  'index' : bigint,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'acceptRun' : ActorMethod<[Id, bigint], [] | [ProductionRun]>,
  'approveSuperSuitPatch' : ActorMethod<[Id], [] | [SuperSuitPatch]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'attachMediaArtifact' : ActorMethod<[AttachMediaInput], [] | [ProductionRun]>,
  'bumpDnaVersion' : ActorMethod<[Id], [] | [DnaRecord]>,
  'clearReplicateToken' : ActorMethod<[], ReplicateTokenStatus>,
  'continueRun' : ActorMethod<[Id, bigint], [] | [ProductionRun]>,
  'createAsset' : ActorMethod<[AssetInput], AssetIngredient>,
  'createCameo' : ActorMethod<[CameoInput], CameoCapture>,
  'createDna' : ActorMethod<[DnaInput], DnaRecord>,
  'createLore' : ActorMethod<[LoreInput], LoreRule>,
  'deleteAsset' : ActorMethod<[Id], boolean>,
  'deleteCameo' : ActorMethod<[Id], boolean>,
  'deleteDna' : ActorMethod<[Id], boolean>,
  'deleteLore' : ActorMethod<[Id], boolean>,
  'deleteMediaArtifact' : ActorMethod<[Id], boolean>,
  'execute' : ActorMethod<[string], Result>,
  'getAgentVersion' : ActorMethod<[AgentKind], [] | [AgentVersion]>,
  'getApiDoc' : ActorMethod<[], string>,
  'getAsset' : ActorMethod<[Id], [] | [AssetIngredient]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCameo' : ActorMethod<[Id], [] | [CameoCapture]>,
  'getCostTelemetry' : ActorMethod<[], CostTelemetry>,
  'getDna' : ActorMethod<[Id], [] | [DnaRecord]>,
  'getEntropyState' : ActorMethod<[], EntropyState>,
  'getLore' : ActorMethod<[Id], [] | [LoreRule]>,
  'getMediaArtifact' : ActorMethod<[Id], [] | [MediaArtifact]>,
  'getReplicateTokenStatus' : ActorMethod<[], ReplicateTokenStatus>,
  'getRevision' : ActorMethod<[Id, bigint], [] | [Revision]>,
  'getRun' : ActorMethod<[Id], [] | [ProductionRun]>,
  'getRunDecision' : ActorMethod<[Id], [] | [RunDecisionState]>,
  'getSuperSuitPatch' : ActorMethod<[Id], [] | [SuperSuitPatch]>,
  'getVideoGeneration' : ActorMethod<[Id], [] | [VideoGeneration]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAssets' : ActorMethod<[], Array<AssetIngredient>>,
  'listAssetsForCharacter' : ActorMethod<[Id], Array<AssetIngredient>>,
  'listCameos' : ActorMethod<[], Array<CameoCapture>>,
  'listCameosForCharacter' : ActorMethod<[Id], Array<CameoCapture>>,
  'listDna' : ActorMethod<[], Array<DnaRecord>>,
  'listLore' : ActorMethod<[], Array<LoreRule>>,
  'listRevisions' : ActorMethod<[Id], Array<Revision>>,
  'listRunDecisions' : ActorMethod<[], Array<[Id, RunDecisionState]>>,
  'listRunPrompts' : ActorMethod<[Id], Array<VideoPromptOption>>,
  'listRuns' : ActorMethod<[], Array<RunSummary>>,
  'listSimulationLogs' : ActorMethod<[Id], Array<SimulationLog>>,
  'listSuperSuitPatches' : ActorMethod<[], Array<SuperSuitPatch>>,
  'listVideoModels' : ActorMethod<[], Array<VideoModel>>,
  'pollVideoGeneration' : ActorMethod<[Id], [] | [VideoGeneration]>,
  'recoverVideoGeneration' : ActorMethod<[Id], [] | [VideoGeneration]>,
  'rejectRun' : ActorMethod<[Id, [] | [string]], [] | [ProductionRun]>,
  'rejectSuperSuitPatch' : ActorMethod<[Id], [] | [SuperSuitPatch]>,
  'rerunVideoGeneration' : ActorMethod<
    [RerunVideoGenerationInput],
    [] | [VideoGeneration]
  >,
  'rollbackAgentVersion' : ActorMethod<[AgentKind], [] | [AgentVersion]>,
  'runCriticAgent' : ActorMethod<[], [] | [SuperSuitPatch]>,
  'schema' : ActorMethod<[], string>,
  'setLoreStatus' : ActorMethod<[Id, LoreStatus], [] | [LoreRule]>,
  'setReplicateToken' : ActorMethod<[string], ReplicateTokenStatus>,
  'startProductionRun' : ActorMethod<[RunInput], ProductionRun>,
  'startVideoGeneration' : ActorMethod<
    [StartVideoGenerationInput],
    [] | [VideoGeneration]
  >,
  'submitTweak' : ActorMethod<[TweakInput], [] | [Revision]>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAsset' : ActorMethod<[Id, AssetInput], [] | [AssetIngredient]>,
  'updateCameo' : ActorMethod<[Id, CameoInput], [] | [CameoCapture]>,
  'updateDna' : ActorMethod<[Id, DnaInput], [] | [DnaRecord]>,
  'updateLore' : ActorMethod<[Id, LoreInput], [] | [LoreRule]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];